<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-05-15T19:51:17 CEST" name="Default suite" finished-at="2020-05-15T19:52:05 CEST" duration-ms="47995">
    <groups>
    </groups>
    <test started-at="2020-05-15T19:51:17 CEST" name="Default test" finished-at="2020-05-15T19:52:05 CEST" duration-ms="47995">
      <class name="page.tests.LogInShould">
        <test-method signature="NotLogWithoutPassword()[pri:0, instance:page.tests.LogInShould@18ce0030]" started-at="2020-05-15T19:51:17 CEST" name="NotLogWithoutPassword" finished-at="2020-05-15T19:51:28 CEST" duration-ms="11599" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NotLogWithoutPassword -->
        <test-method signature="NotLogWithoutUsername()[pri:0, instance:page.tests.LogInShould@18ce0030]" started-at="2020-05-15T19:51:28 CEST" name="NotLogWithoutUsername" finished-at="2020-05-15T19:51:39 CEST" duration-ms="10774" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NotLogWithoutUsername -->
        <test-method signature="NotLogWithoutUsernameAndPassword()[pri:0, instance:page.tests.LogInShould@18ce0030]" started-at="2020-05-15T19:51:39 CEST" name="NotLogWithoutUsernameAndPassword" finished-at="2020-05-15T19:51:49 CEST" duration-ms="9661" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [https://sandbox.2checkout.com/sandbox] but found [https://sandbox.2checkout.com/sandbox/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://sandbox.2checkout.com/sandbox] but found [https://sandbox.2checkout.com/sandbox/login]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at page.tests.LogInShould.NotLogWithoutUsernameAndPassword(LogInShould.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NotLogWithoutUsernameAndPassword -->
        <test-method signature="logOneUser()[pri:0, instance:page.tests.LogInShould@18ce0030]" started-at="2020-05-15T19:51:49 CEST" name="logOneUser" finished-at="2020-05-15T19:52:05 CEST" duration-ms="15907" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOneUser -->
      </class> <!-- page.tests.LogInShould -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
